### ISSUE TITLE
Other ways to implement parseGuess?

### ISSUE THREAD

**Issue by briancavalier** [pittsburgh-haskell/haskell-intro-session#2]
I was trying to figure out other ways to implement [`parseGuess`](https://github.com/pittsburgh-haskell/haskell-intro-session/blob/master/answersrc/Main.hs#L75-L82), beyond pattern matching on all 7 cases.

Here's what I came up with:

``` hs
import Data.Maybe (listToMaybe)
-- ...
parseGuess :: String -> Maybe Int
parseGuess s =
  allow $ fmap fst $ listToMaybe $ reads s
  where
    allow (Just i) = if i >= 0 && i <= 6 then Just i else Nothing
    allow Nothing = Nothing
```

Which seems way too complicated, and requires importing `listToMaybe` from `Data.Maybe`.  To be honest, I think the explicit 7-case pattern match is much easier to read.

What are some other ways to do it?

**Comment by FranklinChen** [comment]
Great question! There are a couple of other approaches, especially as there become too many cases to hardcode.

First of all, I advocate using a parser generator library in basically all cases of parsing, because of flexibility and error reporting. `Read` and the like are frowned upon (and in your code, erroneous input such as `1junk` is accepted as return an integer `1`).

So, using [Parsec](https://hackage.haskell.org/package/parsec):

``` haskell
import Text.ParserCombinators.Parsec
import Control.Applicative
import qualified Data.Char as Char

parseGuess :: String -> Maybe Int
parseGuess = eitherToMaybe . parse normalDieParser "console"

-- | Parser for valid die roll 1 to 6.
--
-- >>> let doParse = parse normalDieParser "console"
--
-- >>> doParse "5"
-- Right 5
--
-- >>> doParse "7"
-- Left "console" (line 1, column 1):
-- unexpected "7"
--
-- >>> doParse "junk"
-- Left "console" (line 1, column 1):
-- unexpected "j"
--
-- >>> doParse "1junk"
-- Left "console" (line 1, column 2):
-- unexpected 'j'
-- expecting end of input
normalDieParser :: Parser Int
normalDieParser = (\c -> Char.ord c - Char.ord '1' + 1) <$>
  oneOf ['1'..'6'] <* eof

-- | "Forgetful" utility function that throws away error information.
eitherToMaybe :: Either left right -> Maybe right
eitherToMaybe (Left _) = Nothing
eitherToMaybe (Right a) = Just a
```

**Comment by FranklinChen** [comment]
Also, if you want to generalize to `n`-sided die, here is a way to do it (as something that could be embedded in parsing more tokens than just a number, because otherwise `reads` does the job just fine).

``` haskell
-- | Parser for valid die roll 1 to @numSides@.
-- Tricky part is semantic predicate after getting a number.
--
-- >>> let dieParser17 = makeDieParser 17
-- >>> let doParse = parse dieParser17 "console"
--
-- >>> doParse "5"
-- Right 5
--
-- >>> doParse "18"
-- Left "console" (line 1, column 1):
-- Got number 18 but it is not in [1..17]
--
-- >>> doParse "junk"
-- Left "console" (line 1, column 1):
-- unexpected "j"
-- expecting digit
--
-- >>> doParse "1junk"
-- Left "console" (line 1, column 2):
-- unexpected 'j'
-- expecting digit or end of input
makeDieParser :: Int -> Parser Int
makeDieParser numSides = do
  i <- lookAhead $ read <$> many1 digit <* eof
  if i >= 1 && i <= numSides then
    return i
  else
    fail $ "Got number " ++ show i ++ " but it is not in [1.." ++ show numSides ++ "]"
```

**Comment by FranklinChen** [comment]
And if you want to do something crazy, like generate a parser at compile time, here is a naive one (a real one would actually construct a finite state machine, of course), using Template Haskell.

How to splice in code generated at compile time:

``` haskell
import DieTemplate (generateDieParser)
$(generateDieParser "parseGuess28" 28)
```

The template code, which is tedious (Lisp forever!?) but not too hard to reverse-engineer in this case through a sample expansion:

``` haskell
{-# LANGUAGE TemplateHaskell #-}

module DieTemplate where

import Language.Haskell.TH

-- | Generate source code for a die number parser.
--
-- Use GHCi to reverse-engineer what we want to make.
--
-- Note: don't try to use doctest because of TH complications.
--
-- > runQ [d| foo "1" = Just 1; foo "2" = Just 2; foo "3" = Just 3; foo _ = Nothing |]
-- [FunD foo_3 [Clause [LitP (StringL "1")] (NormalB (AppE (ConE Data.Maybe.Just) (LitE (IntegerL 1)))) [],Clause [LitP (StringL "2")] (NormalB (AppE (ConE Data.Maybe.Just) (LitE (IntegerL 2)))) [],Clause [LitP (StringL "3")] (NormalB (AppE (ConE Data.Maybe.Just) (LitE (IntegerL 3)))) [],Clause [WildP] (NormalB (ConE Data.Maybe.Nothing)) []]]
generateDieParser :: String -- ^ name of function to define
                  -> Integer -- ^ number of sides of the die
                  -> Q [Dec]
generateDieParser funcName numSides = return
  [
    FunD (mkName funcName) $
      map numberClause [1..numSides] ++ [defaultClause]
  ]

-- | Wildcard matches to 'Nothing'
defaultClause :: Clause
defaultClause = Clause
  [WildP]
  (NormalB $
    ConE 'Nothing)
  []

-- | Match the string representation of 'Integer' 'i' to return 'Just' of it.
numberClause :: Integer -> Clause
numberClause i = Clause
  [LitP (StringL $ show i)]
  (NormalB $
    AppE (ConE 'Just)
         (LitE $ IntegerL i))
  []
```

**Comment by FranklinChen** [comment]
Final (?) note: here is an idiomatic version of your implementation that handles the case of junk after digits. No `if`, no "getters" such as `fst`.

``` haskell
-- | Return 'Just' @n@ if the string parses to a valid die roll 1
-- through 6, else 'Nothing'
--
-- >>> readParseGuess "5"
-- Just 5
--
-- >>> readParseGuess "junk"
-- Nothing
--
-- >>> readParseGuess "7"
-- Nothing
--
-- >>> readParseGuess "7junk"
-- Nothing
readParseGuess :: String -> Maybe Int
readParseGuess s =
  case reads s of
    [(i, "")] | i >= 0 && i <= 6 -> Just i
    _ -> Nothing
```

**Comment by briancavalier** [comment]
Wow, @FranklinChen, this is really great info.  Thank you!

The final example looks like the kind of thing I was aiming for (but clearly didn't hit!).  To my eyes, it's the most "obviously correct" version.  I haven't really gotten into parsec yet, but after seeing your examples, and reading a bit of the [parsec chapter in Real World Haskell](http://book.realworldhaskell.org/read/using-parsec.html), I def want to learn more :).  It looks really nice.

Nice job at the meetup, btw :)

**Comment by FranklinChen** [comment]
I'm glad you enjoyed the meetup... I was kind of overwhelmed by the large turnout, should have worked with some people to have them be assistants and stuff. Definitely an experiment on my part!

Regarding parsing for Haskell, I have mixed feelings about Parsec. It did set the standard when it came out 15 years ago, and I guess I still use it by default, but there is also Attoparsec (but that is optimized by operating on bytes and text, rather than being generic, and has bad error reporting), and finally there is the slow but error-reporting-focused Trifecta, which I may use more in the future.

**Comment by briancavalier** [comment]
Ah, cool, Trifecta looks interesting as well.  Thanks again for the help.

**Comment by FranklinChen** [comment]
By the way, a pretty good resource for seeing Parsec in action is this video series: https://www.youtube.com/playlist?list=PL_xuff3BkASMOzBr0hKVKLuSnU4UIinKx

And for the record, the main technical issue with Parsec that is vexing is that it does not backtrack by default, so you have to put in `try`. This is a non-compositional hack that causes problems in large parsers.
